# Generated by Django 5.0 on 2024-05-28 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='pret.materiel')),
                ('possesseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='pret.enseignant')),
            ],
        ),
    ]
