# Generated by Django 5.0 on 2024-05-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0002_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='possesseur_actuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiel_possede', to='pret.enseignant'),
        ),
    ]
