# Generated by Django 5.0 on 2024-06-02 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0003_materiel_possesseur_actuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='budget',
            field=models.CharField(choices=[('annee_courante', "Budget de l'année courante"), ('projet', 'Budget projets'), ('exceptionnel', 'Budget financements exceptionnels')], default='annee_courante', max_length=20),
        ),
        migrations.AddField(
            model_name='materiel',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='possesseur_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiel_possede', to='pret.enseignant'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='accessoires',
            field=models.ManyToManyField(blank=True, to='pret.accessoire'),
        ),
        migrations.CreateModel(
            name='HistoriquePassation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passation', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(blank=True, max_length=100)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('objectif_utilisation', models.TextField(blank=True)),
                ('accessoires', models.ManyToManyField(blank=True, to='pret.accessoire')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='pret.materiel')),
                ('possesseur_actuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuel_historiques', to='pret.enseignant')),
                ('possesseur_precedent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precedent_historiques', to='pret.enseignant')),
            ],
        ),
    ]
