# Generated by Django 5.0 on 2024-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pret', '0004_accessoire_materiel_budget_materiel_montant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepassation',
            name='etat_accessoires',
            field=models.TextField(blank=True),
        ),
    ]
